eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: valdeflix-login
    nonSecurePort: 80    
      
spring:
  application:
    name: valdeflix-login
  