eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.7:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    
spring:
  application:
    name: valdeflix-media

server:
  port: 8002
